# -*- coding: utf-8 -*-
"""calculo_combustivel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jk5FTT-Bt7Qjd5kJznoTN28zx3L898D4
"""

tempoGasto = float(input("Tempo gasto na viagem em horas: "))
velocidadeMedia = float(input("Velocidade média: "))
distancia = tempoGasto * velocidadeMedia
litros_usados = distancia / 12

print(f"\nA velocidade média foi de: {velocidadeMedia} Km/h")
print(f"O tempo gasto na viagem foi de : {tempoGasto} horas")
print(f"A distânncia percorrida foi de : {distancia} Km")
print(f"A quantidade de litros consumidas foi de: {litros_usados} L")