# -*- coding: utf-8 -*-
"""conversao_celcius_fahrenheit_funcao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qKz6birBDfsdx0Gg7-ACQ0q-jlQed92T
"""

def lerTemperatura():
  temperatura = float(input("Digite a temperatura em Celcius: "))
  return temperatura

def calculaTemperatura(temperatura):
  return (9 * temperatura + 160) / 5

def mostraTemperatura(temperatura):
  print(f"A temperatura convertida para Fahrenheit é: {temperatura} °F")

temperatura = lerTemperatura()
resultado = calculaTemperatura(temperatura)
mostraTemperatura(resultado)