# -*- coding: utf-8 -*-
"""dicionario_exercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RH3HC3UgnyBMmfriO3ocxFxBNXbNbCLS
"""

notaAlunos = {}

for i in range(0, 3):
  nome = input("Nome do aluno: ")
  notaAluno = float(input("Nota do aluno: "))
  notaAlunos[nome] = notaAluno

print(notaAlunos)

notas = notaAlunos.values()
soma = 0

for value in notas:
  soma += value

media = soma / 3

print("A média da turma é : {:.2f}".format(media))