# -*- coding: utf-8 -*-
"""idade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14A3ZtMsCksRkYAZ5_bXsfLaHJOsNdE18
"""

idade = int(input("Qual é a sua idade?"))

if idade < 0:
  print("Idade inválida")
elif idade <= 12:
  print("Criança")
elif idade <= 17:
  print("Adolescente")
elif idade >= 18:
  print("Adulto")
else:
  print("Idade inválida")