# -*- coding: utf-8 -*-
"""media_for.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fGQ3oFS48Iz55gUf8j2Y0CQkqEvfVuP9
"""

soma = 0
for i in range(0, 5):
  nota = float(input("Digite sua nota: "))
  soma += nota

print("Sua media é: {:.2f}".format(soma / 5))