# -*- coding: utf-8 -*-
"""operacoes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D_UpT_o3Pmerg6bLwjNvSNEM5YJ_wVSc
"""

numero1 = int(input("Digite o primeiro número: "))
numero2 = int(input("Digite o segundo número: "))

soma = numero1 + numero2
subtracao = numero1 - numero2
multiplicacao = numero1 * numero2
divisao = numero1 / numero2

print(f"A soma entre {numero1} e {numero2} é igual a {soma}")
print(f"A subtracao entre {numero1} e {numero2} é igual a {subtracao}")
print(f"A multiplicacao entre {numero1} e {numero2} é igual a {multiplicacao}")
print(f"A divisao entre {numero1} e {numero2} é igual a {divisao}")