# -*- coding: utf-8 -*-
"""reprovado_ou_aprovado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YwBv-ACSKb5_egTaOhvia50oTtYPx69K
"""

nota1 = float(input("Digite sua primeira nota: "))
nota2 = float(input("Digite sua segunda nota: "))
nota3 = float(input("Digite sua terceira nota: "))

media = (nota1 + nota2 + nota3) / 3

if media <= 4:
  print("Reprovado")
elif media <= 6:
  print("Pegou exame!")
  nota_exame = float(input("Qual a nota do seu exame: "))
  if nota_exame > 6:
    print("Aprovado")
  else:
    print("Reprovado")
elif media <= 10:
  print("APROVADO!")