# -*- coding: utf-8 -*-
"""soma_matriz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Am6sdNFUtngTOT_e7_QWKemznRfVXr4u
"""

import numpy as np

matriz = np.array([[3, 4, 1],
                   [3, 1, 5]])

soma = 0
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    soma += matriz[i][j]

print(soma)