# -*- coding: utf-8 -*-
"""soma_lista.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w72eEopL-_Ktb_rVb3AOPVY6sMG594iA
"""

lista = []
soma = 0

for i in range(0, 5):
  numero = int(input())
  lista.append(numero)

for i in range(len(lista)):
  soma += lista[i]

print(soma)