# -*- coding: utf-8 -*-
"""tabuada.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lOL8mFOTxmwxS_4HKGiKBIwJJfBadIzI
"""

print("Digite um número e mostrarei a tabuada dele!")
numero = int(input("Qual o número que você quer saber a tabuada? "))

for numeroTabuada in range(0, 11):
  resultado = numero * numeroTabuada
  print(f"{numero} x {numeroTabuada} = {resultado}")